CREATE TABLE Vacuna (id_vacunaVac SERIAL NOT NULL, NombreVac varchar(255) NOT NULL, EscencialVac bool NOT NULL, RecomendadaVac bool NOT NULL, EsquemaContinuoVac bool, CondicionEspecialid_condicionCond int4, PRIMARY KEY (id_vacunaVac));
CREATE TABLE Tipo_Vacuna (id_tipoTipo SERIAL NOT NULL, Tipo_vacunaTipo varchar(255) NOT NULL, PRIMARY KEY (id_tipoTipo));
CREATE TABLE Vacuna_Tipo_Vacuna (Vacunaid_vacunaVac int4 NOT NULL, Tipo_Vacunaid_tipoTipo int4 NOT NULL, PRIMARY KEY (Vacunaid_vacunaVac, Tipo_Vacunaid_tipoTipo));
CREATE TABLE Enfermedad (id_enfermedadEnf SERIAL NOT NULL, NombreEnf varchar(255) NOT NULL, PRIMARY KEY (id_enfermedadEnf));
CREATE TABLE Vacuna_Enfermedad (Vacunaid_vacunaVac int4 NOT NULL, Enfermedadid_enfermedadEnf int4 NOT NULL, PRIMARY KEY (Vacunaid_vacunaVac, Enfermedadid_enfermedadEnf));
CREATE TABLE Mascota (id_mascotaMasc SERIAL NOT NULL, nombreMasc varchar(255) NOT NULL, PRIMARY KEY (id_mascotaMasc));
CREATE TABLE Estado (id_estadoEstado SERIAL NOT NULL, NombreEstado varchar(255) NOT NULL, PRIMARY KEY (id_estadoEstado));
CREATE TABLE Esquema (id_esquemaEsq SERIAL NOT NULL, id_vacunaVac int4 NOT NULL, id_mascotaMasc int4 NOT NULL, id_estadoEstado int4 NOT NULL, EdadPrimeraAplicEsq numeric(4, 2), NumeroDosisPrimeraAplicEsq numeric(2, 0), FrecuenciaDosisPrimerAplicEsq varchar(255), IntervaloDosisPrimerAplicEsq numeric(2, 0), EdadRefuerzoEsq numeric(4, 2), NumeroDosisRefuerzoEsq numeric(2, 0), FrecuenciaDosisRefuerzoEsq varchar(255), IntervaloDosisRefuerzoEsq numeric(2, 0), PRIMARY KEY (id_esquemaEsq));
CREATE TABLE Administracion (id_administracionAd SERIAL NOT NULL, NombreAd varchar(255) NOT NULL, PRIMARY KEY (id_administracionAd));
CREATE TABLE Vacuna_Administracion (Vacunaid_vacunaVac int4 NOT NULL, Administracionid_administracionAd int4 NOT NULL, PRIMARY KEY (Vacunaid_vacunaVac, Administracionid_administracionAd));
CREATE TABLE CondicionEspecial (id_condicionCond SERIAL NOT NULL, NombreCond varchar(255) NOT NULL, PRIMARY KEY (id_condicionCond));
ALTER TABLE Vacuna_Tipo_Vacuna ADD CONSTRAINT FKVacuna_Tip530404 FOREIGN KEY (Vacunaid_vacunaVac) REFERENCES Vacuna (id_vacunaVac);
ALTER TABLE Vacuna_Tipo_Vacuna ADD CONSTRAINT FKVacuna_Tip96028 FOREIGN KEY (Tipo_Vacunaid_tipoTipo) REFERENCES Tipo_Vacuna (id_tipoTipo);
ALTER TABLE Vacuna_Enfermedad ADD CONSTRAINT FKVacuna_Enf940514 FOREIGN KEY (Vacunaid_vacunaVac) REFERENCES Vacuna (id_vacunaVac);
ALTER TABLE Vacuna_Enfermedad ADD CONSTRAINT FKVacuna_Enf854881 FOREIGN KEY (Enfermedadid_enfermedadEnf) REFERENCES Enfermedad (id_enfermedadEnf);
ALTER TABLE Esquema ADD CONSTRAINT FKEsquema207082 FOREIGN KEY (id_vacunaVac) REFERENCES Vacuna (id_vacunaVac);
ALTER TABLE Esquema ADD CONSTRAINT FKEsquema731322 FOREIGN KEY (id_mascotaMasc) REFERENCES Mascota (id_mascotaMasc);
ALTER TABLE Esquema ADD CONSTRAINT FKEsquema557222 FOREIGN KEY (id_estadoEstado) REFERENCES Estado (id_estadoEstado);
ALTER TABLE Vacuna_Administracion ADD CONSTRAINT FKVacuna_Adm49114 FOREIGN KEY (Vacunaid_vacunaVac) REFERENCES Vacuna (id_vacunaVac);
ALTER TABLE Vacuna_Administracion ADD CONSTRAINT FKVacuna_Adm595636 FOREIGN KEY (Administracionid_administracionAd) REFERENCES Administracion (id_administracionAd);
ALTER TABLE Vacuna ADD CONSTRAINT FKVacuna940896 FOREIGN KEY (CondicionEspecialid_condicionCond) REFERENCES CondicionEspecial (id_condicionCond);
